# Generated by Django 5.0.4 on 2024-05-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_observe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouseclick',
            name='image',
            field=models.TextField(),
        ),
    ]
